baseURL: "/"
languageCode: "en-us"
title: "No Package Left Behind"

module:
  imports:
  - path: github.com/hugomods/icons/vendors/bootstrap
  - path: github.com/hugomods/icons/vendors/lucide

params:
  icons:
    throw_on_error: true
    vendor: bootstrap 