name: nplb
static_sites:
- build_command: >
   hugo mod init github.come/zjpiazza/nplb-website && \
   hugo --destination ./public
  environment_slug: hugo
  github:
    branch: main
    deploy_on_push: true
    repo: zjpiazza/nplb-site
  name: nplb